name: lovesync
description: LoveSync - ung dung dong bo cam xuc va thau hieu danh cho cap doi.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  http: ^1.2.2
  # --- Anh cho ky niem ---
  image_picker: ^1.1.2        # chup anh / chon tu thu vien
  path_provider: ^2.1.5       # luu anh vao thu muc rieng cua app
  image: ^4.3.0               # thu nho anh de dong bo (thuan Dart)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
